In [138]:
import numpy as np
from scipy import linalg

from copy import deepcopy
import time

In [139]:
A = np.random.rand(1000, 1000)

# Zadanie 1 - Metoda potęgowa
Napisz funkcję obliczającą metodą potęgową dominującą wartość własną (największą co  
do modułu) i odpowiadający jej wektor własny dla danej macierzy rzeczywistej syme-  
trycznej. Sprawdź poprawność działania programu porównując własną implementację  
z wynikami funkcji bibliotecznej. Przedstaw na wykresie zależność czasu obliczeń od  
rozmiaru macierzy (rozmiary macierzy 100x100, 500x500, ...).  
•Powtarzaj mnożenie wektora xi przez macierz A:  
xi+1 = Axi,  
dzieląc za każdym razem wektor wynikowy przez ||xi+1||∞  
•Element wektora xi o największej wartości bezwzględnej zbiega do dominującej  
wartości własnej  
•Przeskalowany wektor xi zbiega do dominującego wektora własnego  
•Obliczenia powinny się zatrzymać po przekroczeniu maksymalnej liczby iteracji,  
albo w przypadku gdy ||xi −xi+1||< ε (kryterium małej poprawki)  
•Pod koniec obliczeń znormalizuj otrzymany wektor własny.  

In [140]:
def metoda_potegowa(A, eps=1e-6, maxIt=10000):
    n = len(A)
    v_k = np.array([1/n] * n)
    delta = 1

    i = 0
    while delta > eps and i < maxIt:
        v_kk = A @ v_k
        lambda_k = np.linalg.norm(v_k, np.inf)
        v_kk = v_kk / lambda_k
        delta = np.linalg.norm(v_k - v_kk)
        v_k = v_kk
        i += 1
    return v_k / np.linalg.norm(v_k), i

In [141]:
def metoda_potegowa_lib(A):
    return np.linalg.eig(A)[1].transpose()[0]

In [142]:
A_copy = deepcopy(A)
eps = 1e-6
max_iter = 10000

start = time.time()
print(metoda_potegowa(A, eps, max_iter))
end = time.time()
print(end - start)

(array([0.0316519 , 0.03112681, 0.03113939, 0.03206278, 0.03114829,
       0.03053655, 0.0312646 , 0.03116638, 0.0316132 , 0.03131558,
       0.03226007, 0.0307698 , 0.03211284, 0.03157465, 0.03215786,
       0.03090921, 0.03195841, 0.03192048, 0.03333567, 0.03105921,
       0.03127633, 0.0312562 , 0.03234453, 0.03122838, 0.03147101,
       0.03096404, 0.03188395, 0.03156202, 0.03081762, 0.03057351,
       0.03221457, 0.03207165, 0.0302153 , 0.03175799, 0.03133251,
       0.03303321, 0.03201506, 0.03105765, 0.03187706, 0.0318864 ,
       0.03274794, 0.03102077, 0.03198128, 0.0312136 , 0.03084373,
       0.0320336 , 0.0310618 , 0.03106522, 0.03104858, 0.03110043,
       0.03261608, 0.03221478, 0.03243869, 0.03139297, 0.03167402,
       0.03122243, 0.03132603, 0.03117028, 0.0312949 , 0.03136217,
       0.03118805, 0.0308005 , 0.0318227 , 0.03200764, 0.03062744,
       0.03249322, 0.03020979, 0.03114266, 0.03125253, 0.0309958 ,
       0.03086332, 0.03288273, 0.03213029, 0.03123166, 0.0303

In [143]:
A_copy = deepcopy(A)
start = time.time()
print(metoda_potegowa_lib(A))
end = time.time()
print(end - start)

[-0.0316519 +0.j -0.03112681+0.j -0.03113939+0.j -0.03206278+0.j
 -0.03114829+0.j -0.03053655+0.j -0.0312646 +0.j -0.03116638+0.j
 -0.0316132 +0.j -0.03131558+0.j -0.03226007+0.j -0.0307698 +0.j
 -0.03211284+0.j -0.03157465+0.j -0.03215786+0.j -0.03090921+0.j
 -0.03195841+0.j -0.03192048+0.j -0.03333567+0.j -0.03105921+0.j
 -0.03127633+0.j -0.0312562 +0.j -0.03234453+0.j -0.03122838+0.j
 -0.03147101+0.j -0.03096404+0.j -0.03188395+0.j -0.03156202+0.j
 -0.03081762+0.j -0.03057351+0.j -0.03221457+0.j -0.03207165+0.j
 -0.0302153 +0.j -0.03175799+0.j -0.03133251+0.j -0.03303321+0.j
 -0.03201506+0.j -0.03105765+0.j -0.03187706+0.j -0.0318864 +0.j
 -0.03274794+0.j -0.03102077+0.j -0.03198128+0.j -0.0312136 +0.j
 -0.03084373+0.j -0.0320336 +0.j -0.0310618 +0.j -0.03106522+0.j
 -0.03104858+0.j -0.03110043+0.j -0.03261608+0.j -0.03221478+0.j
 -0.03243869+0.j -0.03139297+0.j -0.03167402+0.j -0.03122243+0.j
 -0.03132603+0.j -0.03117028+0.j -0.0312949 +0.j -0.03136217+0.j
 -0.03118805+0.j -0.03080

# Zadanie 2 - Odwrotna metoda potęgowa
Opierając się na twierdzeniu o transformacji widma macierzy:  
Twierdzenie 1 Macierz (A−σI)−1 (jeśli istnieje), to ma wartości własne równe 1 /   
λk −σ  
(λk jest k-tą wartością macierzy A) i wektory własne identyczne z macierzą A.  
oraz wykorzystując metodę potęgową i faktoryzację LU zaimplementuj odwrotną metodę  
potęgową pozwalającą na szybkie znalezienie wektorów własnych macierzy A, dla warto-  
ści σ bliskich odpowiedniej wartości własnej. Wykorzystaj fakt, że mnożenie wektora xi  
przez macierz A−1 (xi+1 = A−1xi) odpowiada rozwiązaniu układu równań Axi+1 = xi.  

In [144]:
def odwrotna_metoda_potegowa(A, eps=1e-5, maxIt=10000, sigma=1):
    n = len(A)
    v_k = np.array([1/n] * n)
    B = linalg.inv(A - sigma * np.eye(n))
    delta = 1
    
    lu = linalg.lu_factor(B)
    
    i = 0
    while delta > eps and i < maxIt:
        v_kk = linalg.lu_solve(lu, v_k)
        v_kk = v_kk / np.linalg.norm(v_kk)
        delta = np.linalg.norm(v_k - v_kk)
        v_k = v_kk
        i += 1

    return v_k / np.linalg.norm(v_k), i

In [149]:
A_copy = deepcopy(A)
eps = 1e-6
max_iter = 10000
sigma = 0

start = time.time()
print(odwrotna_metoda_potegowa(A, eps, max_iter, sigma))
end = time.time()
print(end - start)

(array([0.03165189, 0.03112681, 0.03113939, 0.03206278, 0.03114829,
       0.03053655, 0.0312646 , 0.03116638, 0.0316132 , 0.03131558,
       0.03226007, 0.0307698 , 0.03211284, 0.03157465, 0.03215786,
       0.03090921, 0.03195841, 0.03192048, 0.03333567, 0.03105921,
       0.03127633, 0.0312562 , 0.03234453, 0.03122838, 0.03147101,
       0.03096404, 0.03188395, 0.03156202, 0.03081762, 0.03057351,
       0.03221457, 0.03207165, 0.0302153 , 0.03175799, 0.03133251,
       0.03303321, 0.03201506, 0.03105765, 0.03187706, 0.0318864 ,
       0.03274794, 0.03102077, 0.03198128, 0.0312136 , 0.03084373,
       0.0320336 , 0.0310618 , 0.03106522, 0.03104858, 0.03110043,
       0.03261608, 0.03221478, 0.03243869, 0.03139297, 0.03167402,
       0.03122243, 0.03132603, 0.03117028, 0.0312949 , 0.03136217,
       0.03118805, 0.0308005 , 0.0318227 , 0.03200764, 0.03062744,
       0.03249322, 0.03020979, 0.03114266, 0.03125253, 0.0309958 ,
       0.03086332, 0.03288273, 0.03213029, 0.03123166, 0.0303

# Zadanie 3 - Iteracje z ilorazer Rayleigha
Zaimplementuj iteracyjną metodę wyznaczania wartości własnej i skojarzonego z nią  
wektora własnego wykorzystując odwróconą metodę potęgową oraz iloraz Rayleigha.  
Porównaj zbieżność metody ze zbieżnością algorytmu potęgowego (macierz symetryczna  
rzeczywista).  
r(x) = xAxT / xxT  
r(qi) = λi

In [146]:
def raileigh(x, A):
    return (x.transpose() @ A @ x) / (x.transpose() @ x)

def iloraz_rayleigha(A, eps, maxIt, sigma):
    lambda_k = sigma
    n = len(A)
    v_k = np.array([1/n] * n)
    delta = 1

    i = 0
    while delta > eps and i < maxIt:
        B = A - lambda_k * np.eye(n)
        v_kk = np.linalg.solve(B, v_k)
        v_kk = v_kk / np.linalg.norm(v_kk)
        lambda_k = raileigh(v_k, A)
        delta = np.linalg.norm(v_k - v_kk)
        v_k = v_kk

    return v_k / np.linalg.norm(v_k), i

In [148]:
A_copy = deepcopy(A)
eps = 1e-6
max_iter = 10000
sigma = 0

start = time.time()
print(iloraz_rayleigha(A, eps, max_iter, sigma))
end = time.time()
print(end - start)

(array([-0.0316519 , -0.03112681, -0.03113939, -0.03206278, -0.03114829,
       -0.03053655, -0.0312646 , -0.03116638, -0.0316132 , -0.03131558,
       -0.03226007, -0.0307698 , -0.03211284, -0.03157465, -0.03215786,
       -0.03090921, -0.03195841, -0.03192048, -0.03333567, -0.03105921,
       -0.03127633, -0.0312562 , -0.03234453, -0.03122838, -0.03147101,
       -0.03096404, -0.03188395, -0.03156202, -0.03081762, -0.03057351,
       -0.03221457, -0.03207165, -0.0302153 , -0.03175799, -0.03133251,
       -0.03303321, -0.03201506, -0.03105765, -0.03187706, -0.0318864 ,
       -0.03274794, -0.03102077, -0.03198128, -0.0312136 , -0.03084373,
       -0.0320336 , -0.0310618 , -0.03106522, -0.03104858, -0.03110043,
       -0.03261608, -0.03221478, -0.03243869, -0.03139297, -0.03167402,
       -0.03122243, -0.03132603, -0.03117028, -0.0312949 , -0.03136217,
       -0.03118805, -0.0308005 , -0.0318227 , -0.03200764, -0.03062744,
       -0.03249322, -0.03020979, -0.03114266, -0.03125253, -0.0